@baseUrl = https://localhost:7214

@productId = 2779ee47-10b0-4bd7-8342-404006aa1392

###
GET {{baseUrl}}/text

###
GET {{baseUrl}}/json

###
GET {{baseUrl}}/api/products-le-ir/{{productId}}

###
GET {{baseUrl}}/api/products-mr-ir/{{productId}}
